// International/city clients for the 3D portfolio
export const clients = [
  {
    id: 1,
    name: "Acme Corp",
    city: "New York, USA",
    logo: "/public/assets/images/acme_logo.png",
    description: "Enterprise fintech solutions for global markets.",
    primaryColor: "#1e3a8a",
    secondaryColor: "#2563eb",
    year: 2024,
    category: "Fintech",
    icon: "Globe",
    images: ["/public/assets/images/acme_project.png"]
  },
  {
    id: 2,
    name: "Zenith Retail",
    city: "London, UK",
    logo: "/public/assets/images/zenith_logo.png",
    description: "3D e-commerce experience for next-gen shopping.",
    primaryColor: "#be185d",
    secondaryColor: "#f43f5e",
    year: 2025,
    category: "E-commerce",
    icon: "ShoppingCart",
    images: ["/public/assets/images/zenith_project.png"]
  },
  {
    id: 3,
    name: "Tokyo Insights",
    city: "Tokyo, Japan",
    logo: "/public/assets/images/tokyo_logo.png",
    description: "Interactive analytics dashboard for business KPIs.",
    primaryColor: "#0d9488",
    secondaryColor: "#22d3ee",
    year: 2025,
    category: "Analytics",
    icon: "BarChart",
    images: ["/public/assets/images/tokyo_project.png"]
  },
  {
    id: 4,
    name: "Berlin Mobility",
    city: "Berlin, Germany",
    logo: "/public/assets/images/berlin_logo.png",
    description: "Smart mobility platform for urban transport.",
    primaryColor: "#f59e42",
    secondaryColor: "#fbbf24",
    year: 2024,
    category: "Mobility",
    icon: "Car",
    images: ["/public/assets/images/berlin_project.png"]
  },
  {
    id: 5,
    name: "Munich HealthTech",
    city: "Munich, Germany",
    logo: "/public/assets/images/german_international_logo.png",
    description: "AI-powered telemedicine platform for European clinics.",
    primaryColor: "#0ea5e9",
    secondaryColor: "#38bdf8",
    year: 2025,
    category: "HealthTech",
    icon: "HeartPulse",
    images: ["/public/assets/images/no_image.png"]
  },
  {
    id: 6,
    name: "Paris Creatives",
    city: "Paris, France",
    logo: "/public/assets/images/no_image.png",
    description: "Branding and digital campaigns for luxury fashion.",
    primaryColor: "#e11d48",
    secondaryColor: "#f472b6",
    year: 2025,
    category: "Creative",
    icon: "Feather",
    images: ["/public/assets/images/no_image.png"]
  },
  {
    id: 7,
    name: "Zurich FinServe",
    city: "Zurich, Switzerland",
    logo: "/public/assets/images/no_image.png",
    description: "Secure fintech APIs for Swiss banking sector.",
    primaryColor: "#16a34a",
    secondaryColor: "#bbf7d0",
    year: 2024,
    category: "Fintech",
    icon: "ShieldCheck",
    images: ["/public/assets/images/no_image.png"]
  },
  {
    id: 8,
    name: "Dubai SmartCity",
    city: "Dubai, UAE",
    logo: "/public/assets/images/no_image.png",
    description: "IoT-powered smart city dashboard for urban planners.",
    primaryColor: "#f59e42",
    secondaryColor: "#fbbf24",
    year: 2025,
    category: "Smart City",
    icon: "Building2",
    images: ["/public/assets/images/no_image.png"]
  },
  {
    id: 9,
    name: "Sydney EdTech",
    city: "Sydney, Australia",
    logo: "/public/assets/images/no_image.png",
    description: "Interactive e-learning platform for APAC schools.",
    primaryColor: "#f43f5e",
    secondaryColor: "#fbbf24",
    year: 2025,
    category: "EdTech",
    icon: "Book",
    images: ["/public/assets/images/no_image.png"]
  },
  {
    id: 10,
    name: "Toronto GreenEnergy",
    city: "Toronto, Canada",
    logo: "/public/assets/images/no_image.png",
    description: "Renewable energy analytics for North American utilities.",
    primaryColor: "#22d3ee",
    secondaryColor: "#0ea5e9",
    year: 2024,
    category: "Energy",
    icon: "Sun",
    images: ["/public/assets/images/no_image.png"]
  }
];
